" vim: filetype=vim
" " " " " " " " " " " " " " " " " " " " " "
"    .  .  .  .  .  .  .  .  .  .  .  .   "
"   .  .  _  .  _  .  .  .|`|  .  .  .    "
"    .  o`.\,=./.`o .  . _|_|_  .  .  .   "
"   .  .  :(o o):  .  .  (o)o) .  .  .    "
"   ---ooO-(._.)-Ooo-ooO-(._.)-Ooo---     "
"    ╔═╗╦╔═╗╦  ╔═╗╔╗╔╔═╗╔╦╗╔═╗╔═╗╔╗╔      "
"    ║  ║║ ║║  ╠═╣║║║╚═╗ ║ ║╣ ║╣ ║║║      "
"    ╚═╝╩╚═╝╩═╝╩ ╩╝╚╝╚═╝ ╩ ╚═╝╚═╝╝╚╝`s    "
"               .vimrc file               "
"                                         "
" " " " " " " " " " " " " " " " " " " " " "
"
" ### Sources
so $HOME/dotfiles/vim/vimplugins

" ### General Settings
    set encoding=utf-8
    " Allow IMproved feature
    set nocompatible
    " # Mouse Integration
        " Enable Mouse use in all modes (NORMAL, INSERT, VISUAL & command-line modes)
            set mouse=a
        " Send more characters for redraws
            set ttyfast
        " GVim Settings
        if !has('gvim')
            set guioptions-=T
            set guifont=Hack\ 12
        endif
    " # Search
        set ignorecase                  " Ignore Captitalization
        set smartcase                   " Use capitalization if capitalized 1 letter
    " # Indentation
        set expandtab                   " Use spaces instead of tabs
        set tabstop=4                   " Set tab lenght in spaces
        " Set indent to correspond to a single tab
        set shiftwidth=4
    " # Hidden Characters (blank lines spaces, tabs)
        set listchars=tab:>-,trail:~,extends:>,precedes:<
        set list
    " # Line Numbers
        set number
        set relativenumber
    " # Interface
        set background=dark
        hi Normal ctermbg=NONE
        " NonText Characters color
        hi NonText ctermfg=240 guifg=#585858
        " Change vertical buffer-split characters for nicer look
        " E.G - Vertical border of NerdTree
        set fillchars+=vert:\║
        " Splits Open at the bottom and right (SANE SPLIT!)
        set splitbelow splitright
        " Block Cursor
            " NeoVim
            set guicursor=n-v-c:block-Cursor/lCursor
            set guicursor=i:block-Cursor/lCursor-blinkon1
            " Vim (For VTE compatible terminals (urxvt, st, xterm, Konsole, etc)
            let &t_SI = "\<Esc>[1 q"
            let &t_EI = "\<Esc>[2 q"
    " Remember line number (position) after exiting a file
        if has("autocmd")
            au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
        endif

" ### Keyboard Mapping
    " # Clipboard Integration 
        " Alias \"anonymous\" register to the \"*\" register 
        set clipboard=unnamedplus
        " Copy to clipboard
        vnoremap  <leader>y  "+y
        nnoremap  <leader>Y  "+yg_
        nnoremap  <leader>y  "+y
        nnoremap  <leader>yy  "+yy
        " Paste from clipboard
        nnoremap <leader>p "+p
        nnoremap <leader>P "+P
        vnoremap <leader>p "+p
        vnoremap <leader>P "+P


    " Command overrides for stupid CAPS LOCK possition
    cnoreabbrev Q q

    " Replace all (%s//g)
    nnoremap SG :%s//g<Left><Left>

    " Write as Sudo
    cmap W w !sudo tee > /dev/null %i

